apiVersion: apps/v1
kind: Deployment
metadata:
  name: appx-api-deployment
  labels:
    app: appx-api
  spec:
    replicas: 2   # le digo cantidad de instancias
    selector:
      matchLabels:
        app: appx-api
    template:
      metadata:
        labels:
          app: appx-api
      spec:
        containers:
        - name: appx-api-container
          image: fabian2112/fabian2112-repo:appx-api-latest # le paso la imagen de mi repo
          ports:
          - containerPort: 8080
          env:
          - name: MYSQL_HOST
            value: mysql-service
        imagePullSecrets:
        - name: regcred   # secreto para acceder a docker-hub
---

# en esta parte de servicios es donde al cluster cerrado le digo como quiero que se comunique con el exterior
apiVersion: v1
kind: Service
metadata:
  name: appx-api-service
spec:
  selector:
    app: appx-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer