version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/sonarqube_data
      - sonarqube_extension:/opt/sonarqube/extension
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    restart: unless-stopped

  jenkins:
    image: fabian2112/fabian2112-repo:jenkins-latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenskins home:/var/jenkins home
    depends_on:
      - sonarqube
    restart: on-failure
  
volumes:
  - 